# This is a basic workflow to help you get started with Actions

name: Telegram notification

# Controls when the action will run. Triggers the workflow on pull request
on: 
  pull_request:
    types:
      - assigned
      - unassigned
      - labeled
      - unlabeled
      - opened
      - edited
      - closed
      - reopened
      - synchronize
      - converted_to_draft
      - ready_for_review
      - locked
      - unlocked
      - review_requested
      - review_request_removed
      - auto_merge_enabled
      - auto_merge_disabled
    

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2 
      
      - name: Set env
        run: echo "GITHUB_REF_RART=$(echo $GITHUB_REF | cut -c 6-)" >> $GITHUB_ENV
        
      # Runs the telegram notify action to send a notification
      - name: Telegram Notify
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            ${{ github.actor }}: ${{ github.event.action }} pull request. https://github.com/${{ github.repository }}/${{ env.GITHUB_REF_RART }}/
