# Notifications on pull requests.

name: Telegram notification

# Controls when the action will run. Triggers the workflow on pull request
on: 
  pull_request:
    types:
      - assigned
      - unassigned
      - labeled
      - unlabeled
      - opened
      - edited
      - closed
      - reopened
      - synchronize
      - converted_to_draft
      - ready_for_review
      - locked
      - unlocked
      - review_requested
      - review_request_removed
      - auto_merge_enabled
      - auto_merge_disabled

  pull_request_comment:
    types:
      - submitted

  pull_request_review:
    types:
      - submitted
      - edited
      - dismissed

  pull_request_review_comment:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Set env
        run: echo "GITHUB_REF_PART=$(echo $GITHUB_REF | cut -c 6-)" >> $GITHUB_ENV
        
      - name: Telegram Notify
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            ${{ github.actor }}: ${{ github.event.action }} {{ github.event_name }}. https://github.com/${{ github.repository }}/${{ env.GITHUB_REF_PART }}/
